config/routes.rb
Rails.application.routes.draw do

  resources :batches
  root 'batches#index'

end

app/models/batch.rb
class Batch < ActiveRecord::Base
  has_many :studentbatches
  has_many :students, :through => :studentbatches

  has_many :coursebatches
  has_many :courses, :through => :coursebatches

  has_many :tutorbatches
  has_many :tutors, :through => :tutorbatches
  
end

app/models/course.rb
class Course < ActiveRecord::Base

	has_many :studentcourses
	has_many :students, :through => :studentcourses

	has_many :coursebatches
	has_many :batches, :through => :coursebatches
end

app/models/coursebatch.rb
class Coursebatch < ActiveRecord::Base

	belongs_to :course
	belongs_to :batch
end

app/models/source.rb
class Source < ActiveRecord::Base

	has_many :studentsources
	has_many :students, :through => :studentsources
end

app/models/student.rb
class Student < ActiveRecord::Base

	has_many :studentsources
	has_many :sources, :through => :studentsources

	has_many :studentbatches
	has_many :batches, :through => :studentbatches

    has_many :studentcourses
    has_many :courses, :through => :studentcourses

    
end

app/models/studentbatch.rb
class Studentbatch < ActiveRecord::Base
	
	belongs_to :batch
	belongs_to :student
	
end

app/models/studentcourse.rb
class Studentcourse < ActiveRecord::Base

	belongs_to :course
	belongs_to :student
end

app/models/studentsource.rb
class Studentsource < ActiveRecord::Base

	belongs_to :student
	belongs_to :source
end

app/models/tutor.rb
class Tutor < ActiveRecord::Base

	has_many :tutorbatches
	has_many :batches, :through => :tutorbatches

	
end

app/models/tutorbatch.rb
class Tutorbatch < ActiveRecord::Base

	belongs_to :tutor
	belongs_to :batch
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
	def index
		@batches = Batch.all
	end

	def new
		@batch = Batch.new
		
	end

	def create
		@batch = Batch.new(batch_params)	
		if @batch.save
			redirect_to batches_path
		else
			render action: "new"	
		end	
	end

	def show
		begin
			@batch = Batch.find(params[:id]) 
		rescue ActiveRecord::RecordNotFound
			redirect_to root_url, notice: " Record Does Not Exist"	
		end	
	end

	def update
		@batch = Batch.find(params[:id])
		if @batch.update_attributes(batch_params)
			redirect_to batches_path, notice: "Sucessufully updated"
		else
			render action: "edit"
		end	
	end

	def destroy
		@batch = Batch.find(params[:id])
		@batch.destroy
		redirect_to batches_path
	end

	def edit
		@batch = Batch.find(params[:id])
	    rescue ActiveRecord::RecordNotFound
		redirect_to root_url, notice: "Record Does Not Exist"
	
	end

	private
	def batch_params
		params[:batch].permit(:name, :start_date, :end_date, :instruction_type, :description, :created_at, :updated_at)
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/views/batches/edit.html.erb
<h3>Edit batches</h3>

<%= form_for @batch do |f|%>

	<% if @batch.errors.any? %>
        <ul>
            <% for msg in @batch.errors.full_messages %>
            <li><%= msg %></li>
            <% end %>
        </ul>
	<% end %>

	<label> Name :</label>
<%= f.text_field :name %><br/>

<lable>Start Date :</lable>
<%= f.text_field :start_date %><br/>

<lable>End Date :</lable>
<%= f.text_field :end_date %><br/>

<label>Instruction Type :</label>
<%= f.text_field :instruction_type %><br/>

<label>Description :</label>
<%= f.text_field :description %><br/>

<label>Created Date :</label>
<%= f.text_field :created_at %><br/>

<label>Updated Date :</label>
<%= f.text_field :updated_at %><br/><br/><br/>

<%= f.submit %>
<%end%>

app/views/batches/index.html.erb
<h3> Listing Batches </h3>
<table border "1">
	<thead>
		<tr>
		<th>sl</th>
			<th>Name</th>
			<th>Start date</th>
			<th>End Date</th>
			<th>Instruction Type</th>
			<th>Description</th>
			<th>Created Date</th>
			<th>Updated Date</th>
		</tr>
	</thead>
	<tbody>
		 <% @batches.each_with_index do |batch,index| %>
             <tr>
                  <td><%= index + 1 %></td>
                  <td><%= batch.name %></td>
                  <td><%= batch.start_date %></td>
                  <td><%= batch.end_date %></td>
                  <td><%= batch.instruction_type %></td>
                  <td><%= batch.description %></td>
                  <td><%= batch.created_at%></td>
                  <td><%= batch.updated_at%></td>
                  <td><%= link_to "Edit", edit_batch_path(batch.id) %> |
                       <%= link_to "Delete", batch_path(batch.id), method: :delete, data: {confirm: "Are you sure?"} %> | 
                       <%= link_to "Show", batch_path(batch.id) %></td>
             </tr>
             <% end %>
	</tbody>


</table>

<%= link_to "Add batch", new_batch_path %>

app/views/batches/new.html.erb
<h3> Add New Batch</h3>

<%= form_for (@batch) do |f| %>

<% if @batch.errors.any? %>
        <ul>
            <% for msg in @batch.errors.full_messages %>
            <li><%= msg %></li>
            <% end %>
        </ul>
	<% end %>

<label> Name :</label>
<%= f.text_field :name %><br/>

<lable>Start Date :</lable>
<%= f.text_field :start_date %><br/>

<lable>End Date :</lable>
<%= f.text_field :end_date %><br/>

<label>Instruction Type :</label>
<%= f.text_field :instruction_type %><br/>

<label>Description :</label>
<%= f.text_field :description %><br/>

<label>Created Date :</label>
<%= f.text_field :created_at %><br/>

<label>Updated Date :</label>
<%= f.text_field :updated_at %><br/><br/><br/>

<%= f.submit %>
<%end%>

app/views/batches/show.html.erb
<div> 
	<strong> Name :</strong>
	<%= @batch.name%>
</div>

<div>
<Strong>Start Date :</strong>
<%= @batch.start_date %>
</div>

<div>
<strong>End Date :</strong>
<%= @batch.end_date %>
</div>

<div>
<strong>Instruction Type :</strong>
<%= @batch.instruction_type %>
</div>

<div>
<strong>Description :</strong>
<%= @batch.description %>
</div>

<div>
<strong>Created Date :</strong>
<%= @batch.created_at %>
</div>

<div>
<strong>Updated Date :</strong>
<%= @batch.updated_at %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sanstha</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>